// Code generated by mockery v2.0.4. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// WebMoneySignerInterface is an autogenerated mock type for the WebMoneySignerInterface type
type WebMoneySignerInterface struct {
	mock.Mock
}

// Sign provides a mock function with given fields: data
func (_m *WebMoneySignerInterface) Sign(data string) (string, error) {
	ret := _m.Called(data)

	var r0 string
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(data)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(data)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
